# config/packages/security.yaml
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    providers:
        #users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\Member
                property: email
    firewalls:
        login:
            pattern: ^/api/login
            stateless: false
            provider: app_user_provider
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        admin_area:
            pattern: ^/admin
            stateless: false
            jwt: ~
            logout:
                path: app_logout
                target: /login
        member_area:
            pattern: ^/profile
            stateless: false
            jwt: ~
            logout:
                path: app_logout
                target: /login

        home_area:
            pattern: /
            stateless: false
            jwt: ~


    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: /, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_USER }
